### ISSUE TITLE
Microsoft.PowerShell_profile.ps1

### ISSUE THREAD

**Issue by BanterBoy** [sdwheeler/tools-by-sean#3]
Hello Sean,

As part of my learning strategy for PowerShell I have been reading through a lot of other users PowerShell Scripts and Modules in order to learn new techniques and methodologies that people are using when writing their code.

During a random series of clicks while browsing GitHub, I have found what I believe to be a potential security issue that you may be unaware of.

You have published your PowerShell profile in this repository and it seems to contain credentials for xAdministrator which appear to be used to connect to virtual machines on usgovcloudapi.net

https://github.com/sdwheeler/tools-by-sean/blob/master/modules/Microsoft.PowerShell_profile.ps1

I am sure it is not an issue as they are likely to be secured with 2FA and some firewall rules but thought it prudent to let you know in case this was published in error.

Kind regards

Luke

**Comment by sdwheeler** [comment]
Thanks for the heads up.
